#pragma once

#include "PulsarionCore/Core.hpp"

#ifdef PULSARION_WINDOWING_BUILD_DLL
#define PULSARION_WINDOWING_API PULSARION_DLL_EXPORT
#else
#define PULSARION_WINDOWING_API PULSARION_DLL_IMPORT
#endif

#ifndef PULSARION_WINDOWING_NO_ADDITIONAL_FEATURES
#define PULSARION_WINDOWING_USE_ADDITIONAL_FEATURES
#endif

#ifdef PULSARION_WINDOWING_USE_ADDITIONAL_FEATURES
#define PULSARION_WINDOWING_LIMIT_EVENTS // Limit the events without side effects to once per PollEvents call
#endif
